PARAMETER FKPOT(CCCRRRAAA,FFF) "Fuel potential restriction by geography (MW)"
/
$ontext

DK_E                 . WIND             1520
DK_W                 . WIND             6480

SE_N                 . WIND             19026
SE_M                 . WIND             9887
SE_S                 . WIND             6087

NO_N                 . WIND             4857
NO_M                 . WIND             5650
NO_S                 . WIND             2793
NO_O                 . WIND             701

*DE_NW                . WIND             7953
*DE_NE                . WIND             7953

DE_NW                . WIND             17000  /*11000*/
DE_NE                . WIND             5000   /*5000*/
DE_CS                . WIND             82746

FI_R                 . WIND             15000




*---------------------------------------------------

*DK_E                 . SUN              3600
*DK_W                 . SUN              5400

*SE_S                 . SUN              3600


*DE_NW                . SUN              16123.7
*DE_NE                . SUN              16123.7
*DE_CS                . SUN              167752.6

$offtext

/;
