*Last time modified (Amalia, 20-06-2015)
*Biogas potential was moved from here to GEQF, as it has to be used (biogas is a waste management technology)
*It seems the biogas potential where wrong (exponential was 1 unit lower) (they were ten times smaller)
Parameter GMAXF(YYY,CCCRRRAAA,FFF) Maximum fuel use (GJ) per year/

*------------------------------------------------------
*DATA THAT ARE SCENARIO DEPENDANT
*------------------------------------------------------

2050   .   DENMARK   .   STRAW    1.00E-06
2050   .   DENMARK   .   WOOD_WASTE   1.00E-06
2050   .   DENMARK   .   WOOD      1.00E-06
*2050   .   DENMARK   .   NAT_GAS     1.00E-06




*$ontext
*2050   .    DK_E    .    MUNI_WASTE    17852682
*2050   .    DK_W    .    MUNI_WASTE    20428718



*2050    .    DENMARK       .    MUNI_WASTE    38281400


2050    .    FINLAND       .    MUNI_WASTE    29000000
2050    .    GERMANY       .    MUNI_WASTE    57600000
2050    .    NORWAY        .    MUNI_WASTE    24275695
2050    .    SWEDEN        .    MUNI_WASTE    56000000
*$offtext




$ontext

*W I N D    E N E R G Y    S C E N A R I O

*Local biomass potentials available for electricity

2020   .   DENMARK   .   STRAW   1.15E+08
2025   .   DENMARK   .   STRAW   1.15E+08
2030   .   DENMARK   .   STRAW   1.15E+08
2035   .   DENMARK   .   STRAW   1.15E+08
2040   .   DENMARK   .   STRAW   8.53E+07
2045   .   DENMARK   .   STRAW   5.57E+07
2050   .   DENMARK   .   STRAW   2.60E+07



*B I O M A S S    S C E N A R I O

*Local biomass potentials available for electricity

2020   .   DENMARK   .   STRAW    1.11E+08
2025   .   DENMARK   .   STRAW    1.11E+08
2030   .   DENMARK   .   STRAW    1.11E+08
2035   .   DENMARK   .   STRAW    1.11E+08
2040   .   DENMARK   .   STRAW    7.40E+07
2045   .   DENMARK   .   STRAW    3.70E+07
2050   .   DENMARK   .   STRAW    0.00E+00
$offtext

*------------------------------------------------------
*DATA THAT ARE NOT SCENARIO DEPENDANT
*------------------------------------------------------
*Local biomass potentials available for electricity

2020   .   NORWAY   .   STRAW         6.00E+06
2025   .   NORWAY   .   STRAW         6.00E+06
2030   .   NORWAY   .   STRAW         6.00E+06
2035   .   NORWAY   .   STRAW         6.00E+06
2040   .   NORWAY   .   STRAW         6.00E+06
2045   .   NORWAY   .   STRAW         6.00E+06
2050   .   NORWAY   .   STRAW         6.00E+06

2020   .   SWEDEN   .   STRAW         1.70E+07
2025   .   SWEDEN   .   STRAW         1.70E+07
2030   .   SWEDEN   .   STRAW         1.70E+07
2035   .   SWEDEN   .   STRAW         1.70E+07
2040   .   SWEDEN   .   STRAW         1.70E+07
2045   .   SWEDEN   .   STRAW         1.70E+07
2050   .   SWEDEN   .   STRAW         1.70E+07

2020   .   FINLAND   .   STRAW        1.30E+07
2025   .   FINLAND   .   STRAW        1.30E+07
2030   .   FINLAND   .   STRAW        1.30E+07
2035   .   FINLAND   .   STRAW        1.30E+07
2040   .   FINLAND   .   STRAW        1.30E+07
2045   .   FINLAND   .   STRAW        1.30E+07
2050   .   FINLAND   .   STRAW        1.30E+07

2020   .   GERMANY   .   STRAW        1.42E+08
2025   .   GERMANY   .   STRAW        1.42E+08
2030   .   GERMANY   .   STRAW        1.42E+08
2035   .   GERMANY   .   STRAW        1.42E+08
2040   .   GERMANY   .   STRAW        1.42E+08
2045   .   GERMANY   .   STRAW        1.42E+08
2050   .   GERMANY   .   STRAW        1.42E+08

2020   .   DENMARK   .   WOOD_WASTE   1.00E-06
2025   .   DENMARK   .   WOOD_WASTE   1.00E-06
2030   .   DENMARK   .   WOOD_WASTE   1.00E-06
2035   .   DENMARK   .   WOOD_WASTE   1.00E-06
2040   .   DENMARK   .   WOOD_WASTE   1.00E-06
2045   .   DENMARK   .   WOOD_WASTE   1.00E-06
*2050   .   DENMARK   .   WOOD_WASTE   1.00E-06

2020   .   NORWAY   .   WOOD_WASTE    1.00E-06
2025   .   NORWAY   .   WOOD_WASTE    1.00E-06
2030   .   NORWAY   .   WOOD_WASTE    1.00E-06
2035   .   NORWAY   .   WOOD_WASTE    1.00E-06
2040   .   NORWAY   .   WOOD_WASTE    1.00E-06
2045   .   NORWAY   .   WOOD_WASTE    1.00E-06
2050   .   NORWAY   .   WOOD_WASTE    1.00E-06

2020   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2025   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2030   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2035   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2040   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2045   .   SWEDEN   .   WOOD_WASTE    9.00E+07
2050   .   SWEDEN   .   WOOD_WASTE    9.00E+07

2020   .   FINLAND   .   WOOD_WASTE   1.20E+08
2025   .   FINLAND   .   WOOD_WASTE   1.20E+08
2030   .   FINLAND   .   WOOD_WASTE   1.20E+08
2035   .   FINLAND   .   WOOD_WASTE   1.20E+08
2040   .   FINLAND   .   WOOD_WASTE   1.20E+08
2045   .   FINLAND   .   WOOD_WASTE   1.20E+08
2050   .   FINLAND   .   WOOD_WASTE   1.20E+08

2020   .   GERMANY   .   WOOD_WASTE   1.00E-06
2025   .   GERMANY   .   WOOD_WASTE   1.00E-06
2030   .   GERMANY   .   WOOD_WASTE   1.00E-06
2035   .   GERMANY   .   WOOD_WASTE   1.00E-06
2040   .   GERMANY   .   WOOD_WASTE   1.00E-06
2045   .   GERMANY   .   WOOD_WASTE   1.00E-06
2050   .   GERMANY   .   WOOD_WASTE   1.00E-06

$ontext
2020   .   DENMARK   .   WOOD      4.00E+07
2025   .   DENMARK   .   WOOD      4.00E+07
2030   .   DENMARK   .   WOOD      4.00E+07
2035   .   DENMARK   .   WOOD      4.00E+07
2040   .   DENMARK   .   WOOD      4.00E+07
2045   .   DENMARK   .   WOOD      4.00E+07
2050   .   DENMARK   .   WOOD      4.00E+07

2020   .   NORWAY   .   WOOD       1.27E+08
2025   .   NORWAY   .   WOOD       1.27E+08
2030   .   NORWAY   .   WOOD       1.27E+08
2035   .   NORWAY   .   WOOD       1.27E+08
2040   .   NORWAY   .   WOOD       9.47E+07
2045   .   NORWAY   .   WOOD       6.23E+07
2050   .   NORWAY   .   WOOD       3.00E+07

2020   .   SWEDEN   .   WOOD       3.12E+08
2025   .   SWEDEN   .   WOOD       3.12E+08
2030   .   SWEDEN   .   WOOD       3.12E+08
2035   .   SWEDEN   .   WOOD       3.12E+08
2040   .   SWEDEN   .   WOOD       2.33E+08
2045   .   SWEDEN   .   WOOD       1.54E+08
2050   .   SWEDEN   .   WOOD       7.50E+07

2020   .   FINLAND   .   WOOD      1.69E+08
2025   .   FINLAND   .   WOOD      1.69E+08
2030   .   FINLAND   .   WOOD      1.69E+08
2035   .   FINLAND   .   WOOD      1.69E+08
2040   .   FINLAND   .   WOOD      1.26E+08
2045   .   FINLAND   .   WOOD      8.30E+07
2050   .   FINLAND   .   WOOD      4.00E+07

2020   .   GERMANY   .   WOOD      9.85E+08
2025   .   GERMANY   .   WOOD      9.85E+08
2030   .   GERMANY   .   WOOD      9.85E+08
2035   .   GERMANY   .   WOOD      9.85E+08
2040   .   GERMANY   .   WOOD      7.35E+08
2045   .   GERMANY   .   WOOD      4.86E+08
2050   .   GERMANY   .   WOOD      2.36E+08
$offtext

*Limitations related to fossil fuel consumption

2020   .   DENMARK   .   COAL   1.08E+08
2025   .   DENMARK   .   COAL   1.06E+08
2030   .   DENMARK   .   COAL   1.00E-06
2035   .   DENMARK   .   COAL   1.00E-06
2040   .   DENMARK   .   COAL   1.00E-06
2045   .   DENMARK   .   COAL   1.00E-06
2050   .   DENMARK   .   COAL   1.00E-06

2020   .   NORWAY   .   COAL    1.00E+06
2025   .   NORWAY   .   COAL    1.00E+06
2030   .   NORWAY   .   COAL    1.00E-06
2035   .   NORWAY   .   COAL    1.00E-06
2040   .   NORWAY   .   COAL    1.00E-06
2045   .   NORWAY   .   COAL    1.00E-06
2050   .   NORWAY   .   COAL    1.00E-06

2035   .   SWEDEN   .   COAL    1.00E-06
2040   .   SWEDEN   .   COAL    1.00E-06
2045   .   SWEDEN   .   COAL    1.00E-06
2050   .   SWEDEN   .   COAL    1.00E-06

2035   .   SWEDEN   .   PEAT    1.00E-06
2040   .   SWEDEN   .   PEAT    1.00E-06
2045   .   SWEDEN   .   PEAT    1.00E-06
2050   .   SWEDEN   .   PEAT    1.00E-06

2035   .   FINLAND   .   COAL   1.00E-06
2040   .   FINLAND   .   COAL   1.00E-06
2045   .   FINLAND   .   COAL   1.00E-06
2050   .   FINLAND   .   COAL   1.00E-06

2035   .   FINLAND   .   PEAT   1.00E-06
2040   .   FINLAND   .   PEAT   1.00E-06
2045   .   FINLAND   .   PEAT   1.00E-06
2050   .   FINLAND   .   PEAT   1.00E-06


2020   .   DENMARK   .   NAT_GAS     6.30E+07
2025   .   DENMARK   .   NAT_GAS     6.30E+07
2030   .   DENMARK   .   NAT_GAS     5.90E+07
2035   .   DENMARK   .   NAT_GAS     7.55E+06
2040   .   DENMARK   .   NAT_GAS     7.55E+06
2045   .   DENMARK   .   NAT_GAS     7.55E+06
*2050   .   DENMARK   .   NAT_GAS     7.55E+06

2020   .   NORWAY   .   NAT_GAS      1.10E+07
2025   .   NORWAY   .   NAT_GAS      1.10E+07
2030   .   NORWAY   .   NAT_GAS      4.00E+06
2035   .   NORWAY   .   NAT_GAS      1.00E-06
2040   .   NORWAY   .   NAT_GAS      1.00E-06
2045   .   NORWAY   .   NAT_GAS      1.00E-06
*2050   .   NORWAY   .   NAT_GAS      1.00E-06

2020   .   SWEDEN   .   NAT_GAS      1.60E+07
2025   .   SWEDEN   .   NAT_GAS      1.20E+07
2030   .   SWEDEN   .   NAT_GAS      1.10E+07
2035   .   SWEDEN   .   NAT_GAS      1.00E+07
2040   .   SWEDEN   .   NAT_GAS      4.00E+06
2045   .   SWEDEN   .   NAT_GAS      4.00E+06
*2050   .   SWEDEN   .   NAT_GAS      3.00E+06

2020   .   FINLAND   .   NAT_GAS     5.00E+07
2025   .   FINLAND   .   NAT_GAS     4.30E+07
2030   .   FINLAND   .   NAT_GAS     2.80E+07
2035   .   FINLAND   .   NAT_GAS     1.40E+07
2040   .   FINLAND   .   NAT_GAS     1.30E+07
2045   .   FINLAND   .   NAT_GAS     7.00E+06
*2050   .   FINLAND   .   NAT_GAS     3.00E+06

2020   .   GERMANY   .   NAT_GAS     9.00E+08
2025   .   GERMANY   .   NAT_GAS     9.00E+08
2030   .   GERMANY   .   NAT_GAS     9.00E+08
2035   .   GERMANY   .   NAT_GAS     9.00E+08
2040   .   GERMANY   .   NAT_GAS     9.00E+08
2045   .   GERMANY   .   NAT_GAS     9.00E+08
*2050   .   GERMANY   .   NAT_GAS     9.00E+08

2030   .   DENMARK   .   LIGHTOIL    1.00E-06
2035   .   DENMARK   .   LIGHTOIL    1.00E-06
2040   .   DENMARK   .   LIGHTOIL    1.00E-06
2045   .   DENMARK   .   LIGHTOIL    1.00E-06
2050   .   DENMARK   .   LIGHTOIL    1.00E-06
2030   .   DENMARK   .   FUELOIL     1.00E-06
2035   .   DENMARK   .   FUELOIL     1.00E-06
2040   .   DENMARK   .   FUELOIL     1.00E-06
2045   .   DENMARK   .   FUELOIL     1.00E-06
2050   .   DENMARK   .   FUELOIL     1.00E-06

2035   .   NORWAY   .   LIGHTOIL     1.00E-06
2040   .   NORWAY   .   LIGHTOIL     1.00E-06
2045   .   NORWAY   .   LIGHTOIL     1.00E-06
2050   .   NORWAY   .   LIGHTOIL     1.00E-06
2035   .   NORWAY   .   FUELOIL      1.00E-06
2040   .   NORWAY   .   FUELOIL      1.00E-06
2045   .   NORWAY   .   FUELOIL      1.00E-06
2050   .   NORWAY   .   FUELOIL      1.00E-06

2035   .   SWEDEN   .   LIGHTOIL     1.00E-06
2040   .   SWEDEN   .   LIGHTOIL     1.00E-06
2045   .   SWEDEN   .   LIGHTOIL     1.00E-06
2050   .   SWEDEN   .   LIGHTOIL     1.00E-06
2035   .   SWEDEN   .   FUELOIL      1.00E-06
2040   .   SWEDEN   .   FUELOIL      1.00E-06
2045   .   SWEDEN   .   FUELOIL      1.00E-06
2050   .   SWEDEN   .   FUELOIL      1.00E-06

2030   .   FINLAND   .   LIGHTOIL    1.00E-06
2035   .   FINLAND   .   LIGHTOIL    1.00E-06
2040   .   FINLAND   .   LIGHTOIL    1.00E-06
2045   .   FINLAND   .   LIGHTOIL    1.00E-06
2050   .   FINLAND   .   LIGHTOIL    1.00E-06
2030   .   FINLAND   .   FUELOIL     1.00E-06
2035   .   FINLAND   .   FUELOIL     1.00E-06
2040   .   FINLAND   .   FUELOIL     1.00E-06
2045   .   FINLAND   .   FUELOIL     1.00E-06
2050   .   FINLAND   .   FUELOIL     1.00E-06


*  NO -- CCS technologies

2020   .   DENMARK   .   COAL_CCS    1.00E-06
2025   .   DENMARK   .   COAL_CCS    1.00E-06
2030   .   DENMARK   .   COAL_CCS    1.00E-06
2035   .   DENMARK   .   COAL_CCS    1.00E-06
2040   .   DENMARK   .   COAL_CCS    1.00E-06
2045   .   DENMARK   .   COAL_CCS    1.00E-06
2050   .   DENMARK   .   COAL_CCS    1.00E-06

2020   .   NORWAY   .   COAL_CCS     1.00E-06
2025   .   NORWAY   .   COAL_CCS     1.00E-06
2030   .   NORWAY   .   COAL_CCS     1.00E-06
2035   .   NORWAY   .   COAL_CCS     1.00E-06
2040   .   NORWAY   .   COAL_CCS     1.00E-06
2045   .   NORWAY   .   COAL_CCS     1.00E-06
2050   .   NORWAY   .   COAL_CCS     1.00E-06

2020   .   SWEDEN   .   COAL_CCS     1.00E-06
2025   .   SWEDEN   .   COAL_CCS     1.00E-06
2030   .   SWEDEN   .   COAL_CCS     1.00E-06
2035   .   SWEDEN   .   COAL_CCS     1.00E-06
2040   .   SWEDEN   .   COAL_CCS     1.00E-06
2045   .   SWEDEN   .   COAL_CCS     1.00E-06
2050   .   SWEDEN   .   COAL_CCS     1.00E-06

2020   .   FINLAND   .   COAL_CCS    1.00E-06
2025   .   FINLAND   .   COAL_CCS    1.00E-06
2030   .   FINLAND   .   COAL_CCS    1.00E-06
2035   .   FINLAND   .   COAL_CCS    1.00E-06
2040   .   FINLAND   .   COAL_CCS    1.00E-06
2045   .   FINLAND   .   COAL_CCS    1.00E-06
2050   .   FINLAND   .   COAL_CCS    1.00E-06

2020   .   GERMANY   .   COAL_CCS    1.00E-06
2025   .   GERMANY   .   COAL_CCS    1.00E-06
2030   .   GERMANY   .   COAL_CCS    1.00E-06
2035   .   GERMANY   .   COAL_CCS    1.00E-06
2040   .   GERMANY   .   COAL_CCS    1.00E-06
2045   .   GERMANY   .   COAL_CCS    1.00E-06
2050   .   GERMANY   .   COAL_CCS    1.00E-06

2020   .   DENMARK   .   NG_CCS      1.00E-06
2025   .   DENMARK   .   NG_CCS      1.00E-06
2030   .   DENMARK   .   NG_CCS      1.00E-06
2035   .   DENMARK   .   NG_CCS      1.00E-06
2040   .   DENMARK   .   NG_CCS      1.00E-06
2045   .   DENMARK   .   NG_CCS      1.00E-06
2050   .   DENMARK   .   NG_CCS      1.00E-06

2020   .   NORWAY   .   NG_CCS       1.00E-06
2025   .   NORWAY   .   NG_CCS       1.00E-06
2030   .   NORWAY   .   NG_CCS       1.00E-06
2035   .   NORWAY   .   NG_CCS       1.00E-06
2040   .   NORWAY   .   NG_CCS       1.00E-06
2045   .   NORWAY   .   NG_CCS       1.00E-06
2050   .   NORWAY   .   NG_CCS       1.00E-06

2020   .   SWEDEN   .   NG_CCS       1.00E-06
2025   .   SWEDEN   .   NG_CCS       1.00E-06
2030   .   SWEDEN   .   NG_CCS       1.00E-06
2035   .   SWEDEN   .   NG_CCS       1.00E-06
2040   .   SWEDEN   .   NG_CCS       1.00E-06
2045   .   SWEDEN   .   NG_CCS       1.00E-06
2050   .   SWEDEN   .   NG_CCS       1.00E-06

2020   .   FINLAND   .   NG_CCS      1.00E-06
2025   .   FINLAND   .   NG_CCS      1.00E-06
2030   .   FINLAND   .   NG_CCS      1.00E-06
2035   .   FINLAND   .   NG_CCS      1.00E-06
2040   .   FINLAND   .   NG_CCS      1.00E-06
2045   .   FINLAND   .   NG_CCS      1.00E-06
2050   .   FINLAND   .   NG_CCS      1.00E-06

2020   .   GERMANY   .   NG_CCS      1.53E+08
2025   .   GERMANY   .   NG_CCS      1.53E+08
2030   .   GERMANY   .   NG_CCS      1.53E+08
2035   .   GERMANY   .   NG_CCS      1.53E+08
2040   .   GERMANY   .   NG_CCS      1.53E+08
2045   .   GERMANY   .   NG_CCS      1.53E+08
2050   .   GERMANY   .   NG_CCS      1.00E-06

2020   .   DENMARK   .   WP_CCS      1.00E-06
2025   .   DENMARK   .   WP_CCS      1.00E-06
2030   .   DENMARK   .   WP_CCS      1.00E-06
2035   .   DENMARK   .   WP_CCS      1.00E-06
2040   .   DENMARK   .   WP_CCS      1.00E-06
2045   .   DENMARK   .   WP_CCS      1.00E-06
2050   .   DENMARK   .   WP_CCS      1.00E-06

2020   .   NORWAY   .   WP_CCS       1.00E-06
2025   .   NORWAY   .   WP_CCS       1.00E-06
2030   .   NORWAY   .   WP_CCS       1.00E-06
2035   .   NORWAY   .   WP_CCS       1.00E-06
2040   .   NORWAY   .   WP_CCS       1.00E-06
2045   .   NORWAY   .   WP_CCS       1.00E-06
2050   .   NORWAY   .   WP_CCS       1.00E-06

2020   .   SWEDEN   .   WP_CCS       1.00E-06
2025   .   SWEDEN   .   WP_CCS       1.00E-06
2030   .   SWEDEN   .   WP_CCS       1.00E-06
2035   .   SWEDEN   .   WP_CCS       1.00E-06
2040   .   SWEDEN   .   WP_CCS       1.00E-06
2045   .   SWEDEN   .   WP_CCS       1.00E-06
2050   .   SWEDEN   .   WP_CCS       1.00E-06

2020   .   FINLAND   .   WP_CCS      1.00E-06
2025   .   FINLAND   .   WP_CCS      1.00E-06
2030   .   FINLAND   .   WP_CCS      1.00E-06
2035   .   FINLAND   .   WP_CCS      1.00E-06
2040   .   FINLAND   .   WP_CCS      1.00E-06
2045   .   FINLAND   .   WP_CCS      1.00E-06
2050   .   FINLAND   .   WP_CCS      1.00E-06



2050   .   GERMANY   .   WP_CCS      1.00E-06





*Biogas Potentials in other countries

*Biogas limits

*From 2035

2020  . DENMARK   . BIOGAS_EC    1E-6
2025  . DENMARK   . BIOGAS_EC    1E-6
2030  . DENMARK   . BIOGAS_EC    1E-6
2035  . DENMARK   . BIOGAS_EC    1E-6
2040  . DENMARK   . BIOGAS_EC    1E-6
2045  . DENMARK   . BIOGAS_EC    1E-6
2050  . DENMARK   . BIOGAS_EC    1E-6

2035  . DENMARK   . BIOGAS       1E-6
2040  . DENMARK   . BIOGAS       1E-6
2045  . DENMARK   . BIOGAS       1E-6
2050  . DENMARK   . BIOGAS       1E-6

2035  . DENMARK   . BIOGAS_net   1E-6
2040  . DENMARK   . BIOGAS_net   1E-6
2045  . DENMARK   . BIOGAS_net   1E-6
2050  . DENMARK   . BIOGAS_net   1E-6


*Only Germany has potential for Geothermal energy (source is the JRC-EU Times model documentation)
2014    .    DENMARK      .    GeoEl      1E-6
2020    .    DENMARK      .    GeoEl      1E-6
2025    .    DENMARK      .    GeoEl      1E-6
2030    .    DENMARK      .    GeoEl      1E-6
2035    .    DENMARK      .    GeoEl      1E-6
2040    .    DENMARK      .    GeoEl      1E-6
2045    .    DENMARK      .    GeoEl      1E-6
2050    .    DENMARK      .    GeoEl      1E-6
2014    .    SWEDEN       .    GeoEl      1E-6
2020    .    SWEDEN       .    GeoEl      1E-6
2025    .    SWEDEN       .    GeoEl      1E-6
2030    .    SWEDEN       .    GeoEl      1E-6
2035    .    SWEDEN       .    GeoEl      1E-6
2040    .    SWEDEN       .    GeoEl      1E-6
2045    .    SWEDEN       .    GeoEl      1E-6
2050    .    SWEDEN       .    GeoEl      1E-6
2014    .    FINLAND      .    GeoEl      1E-6
2020    .    FINLAND      .    GeoEl      1E-6
2025    .    FINLAND      .    GeoEl      1E-6
2030    .    FINLAND      .    GeoEl      1E-6
2035    .    FINLAND      .    GeoEl      1E-6
2040    .    FINLAND      .    GeoEl      1E-6
2045    .    FINLAND      .    GeoEl      1E-6
2050    .    FINLAND      .    GeoEl      1E-6
2014    .    NORWAY       .    GeoEl      1E-6
2020    .    NORWAY       .    GeoEl      1E-6
2025    .    NORWAY       .    GeoEl      1E-6
2030    .    NORWAY       .    GeoEl      1E-6
2035    .    NORWAY       .    GeoEl      1E-6
2040    .    NORWAY       .    GeoEl      1E-6
2045    .    NORWAY       .    GeoEl      1E-6
2050    .    NORWAY       .    GeoEl      1E-6

2020    .    GERMANY      .    GeoEl      10910000
2025    .    GERMANY      .    GeoEl      12511667
2030    .    GERMANY      .    GeoEl      14113333
2035    .    GERMANY      .    GeoEl      15715000
2040    .    GERMANY      .    GeoEl      17316667
2045    .    GERMANY      .    GeoEl      18918333
2050    .    GERMANY      .    GeoEl      20520000


/;
