*Last time modified (Raffaele, 16-06-2015)
*Data for Denmark are taken from the energy scenario report by DEA (2035 and 2050), while for 2025
*a linear projection was assumed between 2035 and 2012 (whose data are from the danish energy producer account

PARAMETER INSCAPSOLH(YYY,C) 'Maximum solar thermal installed capacity in the scenario (MW)'

/


2050       . DENMARK   7400



/;

$ontext
2025       . SWEDEN
2025       . NORWAY
2025       . FINLAND
2025       . GERMANY

2035       . SWEDEN
2035       . NORWAY
2035       . FINLAND
2035       . GERMANY

2050       . SWEDEN
2050       . NORWAY
2050       . FINLAND
2050       . GERMANY

$offtext
