*Data from Samfundsøkonomiske beregningsforudsætninger page 18
*Socioeconomic costs of utilising electricity i.e. using the distribution grid is 193 kr/MWh
*193 kr/MWh = 25.9408 EUR/MWh (note 7.44 is used to convert kr to EUR)
*25.9408 EUR2017/MWh = 15.08476 EUR90/MWh (Multiplying factor 0.581505687 , from base year currency converter 2016)

PARAMETER  TAX_DE(CCC) "Consumers tax on electricity consumption (Money/MWh)"
/
$ontext
DENMARK                                                   15.08476
ESTONIA                                                   15.08476
FINLAND                                                   15.08476
GERMANY                                                   15.08476
LATVIA                                                    15.08476
LITHUANIA                                                 15.08476
NORWAY                                                    15.08476
POLAND                                                    15.08476
RUSSIA                                                    15.08476
SWEDEN                                                    15.08476
BELARUS                                                   15.08476
$offtext
/;
