*Last time modified (Amalia, 12-05-2015)
*Danish Energy Agency, Register of wind turbines
*Data on operating and decommisioned wind turbines (as at end of march 2015)

PARAMETER  WNDFLH(AAA) "Full load hours for wind power (hours)"
/








DK_E_Offshore_14       3568
DK_E_Onshore_14        1966
DK_W_Offshore_14       4335
DK_W_Onshore_14        2252
DK_E_Offshore_20       3586
DK_E_Onshore_20        2266
DK_W_Offshore_20       4344
DK_W_Onshore_20        2501
DK_E_Offshore_25       3872
DK_E_Onshore_25        2652
DK_W_Offshore_25       4469
DK_W_Onshore_25        2916
DK_E_Offshore_30       3952
DK_E_Onshore_30        2637
DK_W_Offshore_30       4458
DK_W_Onshore_30        2918
DK_E_Onshore_35        2637
DK_W_Onshore_35        2918


DE_CS_A1                1937
DE_CS_Onshore20         1879
DE_CS_Onshore35         1937
DE_CS_Onshore50         1969

DE_KF_A                 3712
DE_NE_A1                1953
DE_NE_Onshore20         2195
DE_NE_Onshore35         2263
DE_NE_Onshore50         2300

DE_NW_A1                2473
DE_NW_Onshore20         2393
DE_NW_Onshore35         2467
DE_NW_Onshore50         2508
DK_E_Onshore20          2870
DK_E_Onshore35          2959
DK_E_Onshore50          3008
DK_KF_A                 3712
DK_W_Onshore20          3103
DK_W_Onshore35          3199
DK_W_Onshore50          3252
FI_R_Onshore20          1879
FI_R_Onshore35          1937
FI_R_Onshore50          1969
FI_R_Rural              1656
NO_M_Onshore20          2698
NO_M_Onshore35          2782
NO_M_Onshore50          2828
NO_M_Rural              2387
NO_N_Onshore20          3026
NO_N_Onshore35          3120
NO_N_Onshore50          3171
NO_N_Rural              2683
NO_S_Onshore20          2714
NO_S_Onshore35          2798
NO_S_Onshore50          2844
NO_S_Rural              2565
SE_M_Onshore20          2145
SE_M_Onshore35          2212
SE_M_Onshore50          2248
SE_M_Rural              1931
SE_N_Onshore20          2457
SE_N_Onshore35          2533
SE_N_Onshore50          2575
SE_N_Rural              2215
SE_S_Onshore20          1952
SE_S_Onshore35          2013
SE_S_Onshore50          2046
SE_S_Rural              1719
DE_NE_Offshore10        3712
DE_NE_Offshore20        4179
DE_NE_Offshore35        4380
DE_NE_Offshore50        4485
DE_NW_Offshore10        4251
DE_NW_Offshore20        4272
DE_NW_Offshore35        4477
DE_NW_Offshore50        4584


DK_E_Offshore00         3712
DK_E_Offshore10         3466
DK_E_Offshore20         4179
DK_E_Offshore35         4380
DK_E_Offshore50         4485



DK_W_Offshore00         4251
DK_W_Offshore10         3911
DK_W_Offshore20         4261
DK_W_Offshore35         4466
DK_W_Offshore50         4573








FI_R_Offshore10         3155
FI_R_Offshore20         3512
FI_R_Offshore35         3681
FI_R_Offshore50         3769
NO_M_Offshore10         3803
NO_M_Offshore20         3790
NO_M_Offshore35         3972
NO_M_Offshore50         4067
NO_N_Offshore10         3859
NO_N_Offshore20         3760
NO_N_Offshore35         3941
NO_N_Offshore50         4035
NO_S_Offshore10         3476
NO_S_Offshore20         3855
NO_S_Offshore35         4040
NO_S_Offshore50         4137
SE_M_Offshore10         3697
SE_M_Offshore20         3611
SE_M_Offshore35         3784
SE_M_Offshore50         3874
SE_N_Offshore10         3697
SE_N_Offshore20         3162
SE_N_Offshore35         3314
SE_N_Offshore50         3393
SE_S_Offshore10         3697
SE_S_Offshore20         3553
SE_S_Offshore35         3724
SE_S_Offshore50         3813




/;
