* Unit commitment add-on to Balmorel.

* Additional elements in set GDATASET:


GDUC          'Unit commitment: the unit participates in unit commitment (0/1)'
GDUCUNITSIZE  'Standard size of unit type (MW)'
GDUCGMIN      'Unit commitment: minimum production (share of nominal capacity)'
GDUCUCOST     'Unit commitment: startup cost (Money)'
GDUCCOST0     'Unit commitment: fixed hourly cost (Money)'
GDUCF0        'Unit commitment: fixed hourly fuel use (MWh)'

GDUCDCOST     'Unit commitment: shutdown cost (Money)'
GDUCDTMIN     'Unit commitment: minimum down time (hours)'
GDUCUTMIN     'Unit commitment: minimum up time (hours)'

GDUCDURD      'Unit commitment: duration of shut down process (hours)'
GDUCDURU      'Unit commitment: duration of start up process (hours)'
GDUCRAMPU     'Unit commitment: ramp-up limit (MW/h)'
GDUCRAMPD     'Unit commitment: ramp-down limit (MW/h)'
