Set AIND(AAA)   'Individual heating areas'
* These areas are only included if '$Setglobal FV yes' in balopt.opt
/
* Individual heating areas
  DK_E_1_IND
  DK_E_2_IND
  DK_E_3_IND
  DK_E_4_IND
  DK_E_5_IND

  DK_W_1_IND
  DK_W_2_IND
  DK_W_3_IND
  DK_W_4_IND
  DK_W_5_IND
  DK_W_6_IND

  DK_W_AALBORG_IND
  DK_W_AARHUS_IND
  DK_W_TREFOR_IND
  DK_W_ODENSE_IND

  DK_E_Urban_IND
  DK_E_Rural_IND
  DK_W_Urban_IND
  DK_W_Rural_IND

  DK_E_IND
  DK_W_IND

  DK_E_PUREDH_IND
  DK_W_PUREDH_IND
/;
