PARAMETER  ANNUITYC(CCC) "Transforms investment to annual payment (fraction)"
/
DENMARK                                                   0.04
ESTONIA                                                   0.04
FINLAND                                                   0.04
GERMANY                                                   0.04
LATVIA                                                    0.04
LITHUANIA                                                 0.04
NORWAY                                                    0.04
POLAND                                                    0.04
RUSSIA                                                    0.04
SWEDEN                                                    0.04
BELARUS                                                   0.04
/;
