SET  C(CCC) "Countries in the simulation"
/
DENMARK                         "DENMARK"
*ESTONIA                         "ESTONIA"
FINLAND                         "FINLAND"
GERMANY                         "GERMANY"
*LATVIA                          "LATVIA"
*LITHUANIA                       "LITHUANIA"
NORWAY                          "NORWAY"
*POLAND                          "POLAND"
*RUSSIA                          "RUSSIA"
SWEDEN                          "SWEDEN"
*BELARUS                         "BELARUS"

/;

