PARAMETER DEF_STEPS(RRR,SSS,TTT,DF_QP,DEF) "Elastic electricity demands"
/
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_9                                                  0.8200
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_8                                                  0.8400
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_7                                                  0.8800
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_6                                                  0.9200
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_5                                                  0.9600
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_4                                                  0.9800
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_3                                                  0.9900
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_2                                                  0.9950
DK_E                             . S01                              . T001                             . DF_QUANT                         . DEF_D1_1                                                  1.0000
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_9                                                 12.6540
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_8                                                  9.1100
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_7                                                  5.2276
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_6                                                  3.0564
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_5                                                  1.8184
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_4                                                  1.3637
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_3                                                  1.1705
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_2                                                  1.0817
DK_E                             . S01                              . T001                             . DF_PRICE                         . DEF_D1_1                                                  1.0000
/;




