*Last time modified (Amalia, 04-06-2015)
PARAMETER FUELPRICE(YYY,AAA,FFF) "Fuel prices (Money/GJ)"


*DATASOURCES:
*Biomass prices: "Analysis of biomass prices - Future danish prices for straw, wood chips and wood pellets "Final Report"", 18-06-2013 by Ea Energy Analyses. PP. 96.
*Energy crops prices: Analyasis of the meraket for bioenergy - locally and internationally - EA
*Calculation of biodiesel price considering marginal cost at the biorefinery gate: Technology data for advanced bioenergy fuels, 2013, Danish Energy Agency (Anders Evald, Guiling Hy & Morten Tony Hansen)
*Technology assumed for biooil price: biodiesel production by BTL (biomass to liquid) technology with straw as raw material
*BIOGAS PRODUCTION COST: Same reference than biodiesel production, biogas production assumed to be 95% in weight by manure and 5% in weight of energy crops
*Fossil Fuel Prices: NETP 2012

*Orimulsion and peat assumed 92% of coal
*Lignite assumed 50% of coal, because although the international trading price is higher, in Germany, where the lignite is consumed, it is produced nationally

/

2014        .        DK_CA_Kbh        .        NUCLEAR        0.450
2020        .        DK_CA_Kbh        .        NUCLEAR        0.450
2025        .        DK_CA_Kbh        .        NUCLEAR        0.450
2030        .        DK_CA_Kbh        .        NUCLEAR        0.450
2035        .        DK_CA_Kbh        .        NUCLEAR        0.450
2040        .        DK_CA_Kbh        .        NUCLEAR        0.450
2045        .        DK_CA_Kbh        .        NUCLEAR        0.450
2050        .        DK_CA_Kbh        .        NUCLEAR        0.450

2014        .        DK_CA_Kbh        .        NAT_GAS        4.101
2020        .        DK_CA_Kbh        .        NAT_GAS        2.816
2025        .        DK_CA_Kbh        .        NAT_GAS        3.390
2030        .        DK_CA_Kbh        .        NAT_GAS        3.963
2035        .        DK_CA_Kbh        .        NAT_GAS        3.857
2040        .        DK_CA_Kbh        .        NAT_GAS        3.751
2045        .        DK_CA_Kbh        .        NAT_GAS        3.712
2050        .        DK_CA_Kbh        .        NAT_GAS        3.672

2014        .        NO_M_Rural        .        NAT_GAS       3.850
2020        .        NO_M_Rural        .        NAT_GAS       2.584
2025        .        NO_M_Rural        .        NAT_GAS       3.149
2030        .        NO_M_Rural        .        NAT_GAS       3.714
2035        .        NO_M_Rural        .        NAT_GAS       3.610
2040        .        NO_M_Rural        .        NAT_GAS       3.505
2045        .        NO_M_Rural        .        NAT_GAS       3.466
2050        .        NO_M_Rural        .        NAT_GAS       3.427

2014        .        SE_M_Urban        .        NAT_GAS      3.962
2020        .        SE_M_Urban        .        NAT_GAS      2.658
2025        .        SE_M_Urban        .        NAT_GAS      3.240
2030        .        SE_M_Urban        .        NAT_GAS      3.822
2035        .        SE_M_Urban        .        NAT_GAS      3.714
2040        .        SE_M_Urban        .        NAT_GAS      3.607
2045        .        SE_M_Urban        .        NAT_GAS      3.567
2050        .        SE_M_Urban        .        NAT_GAS      3.527

2014        .        DE_CS_A1        .        NAT_GAS     3.906
2020        .        DE_CS_A1        .        NAT_GAS     2.621
2025        .        DE_CS_A1        .        NAT_GAS     3.194
2030        .        DE_CS_A1        .        NAT_GAS     3.768
2035        .        DE_CS_A1        .        NAT_GAS     3.662
2040        .        DE_CS_A1        .        NAT_GAS     3.556
2045        .        DE_CS_A1        .        NAT_GAS     3.517
2050        .        DE_CS_A1        .        NAT_GAS     3.477

2014        .        FI_R_Urban        .        NAT_GAS   3.906
2020        .        FI_R_Urban        .        NAT_GAS   2.621
2025        .        FI_R_Urban        .        NAT_GAS   3.194
2030        .        FI_R_Urban        .        NAT_GAS   3.768
2035        .        FI_R_Urban        .        NAT_GAS   3.662
2040        .        FI_R_Urban        .        NAT_GAS   3.556
2045        .        FI_R_Urban        .        NAT_GAS   3.517
2050        .        FI_R_Urban        .        NAT_GAS   3.477

2014        .        DK_CA_Kbh        .        COAL       1.497
2020        .        DK_CA_Kbh        .        COAL       0.896
2025        .        DK_CA_Kbh        .        COAL       1.050
2030        .        DK_CA_Kbh        .        COAL       1.205
2035        .        DK_CA_Kbh        .        COAL       1.190
2040        .        DK_CA_Kbh        .        COAL       1.175
2045        .        DK_CA_Kbh        .        COAL       1.160
2050        .        DK_CA_Kbh        .        COAL       1.145


2014        .        DK_CA_Kbh        .        FUELOIL     7.105
2020        .        DK_CA_Kbh        .        FUELOIL     3.224
2025        .        DK_CA_Kbh        .        FUELOIL     5.206
2030        .        DK_CA_Kbh        .        FUELOIL     7.188
2035        .        DK_CA_Kbh        .        FUELOIL     7.105
2040        .        DK_CA_Kbh        .        FUELOIL     7.021
2045        .        DK_CA_Kbh        .        FUELOIL     6.938
2050        .        DK_CA_Kbh        .        FUELOIL     6.854

2014        .        DK_CA_Kbh        .        LIGHTOIL    9.781
2020        .        DK_CA_Kbh        .        LIGHTOIL    5.901
2025        .        DK_CA_Kbh        .        LIGHTOIL    7.883
2030        .        DK_CA_Kbh        .        LIGHTOIL    9.864
2035        .        DK_CA_Kbh        .        LIGHTOIL    9.781
2040        .        DK_CA_Kbh        .        LIGHTOIL    9.697
2045        .        DK_CA_Kbh        .        LIGHTOIL    9.614
2050        .        DK_CA_Kbh        .        LIGHTOIL    9.531

2014        .        NO_M_Rural        .        LIGHTOIL   9.383
2020        .        NO_M_Rural        .        LIGHTOIL   5.503
2025        .        NO_M_Rural        .        LIGHTOIL   7.485
2030        .        NO_M_Rural        .        LIGHTOIL   9.467
2035        .        NO_M_Rural        .        LIGHTOIL   9.383
2040        .        NO_M_Rural        .        LIGHTOIL   9.299
2045        .        NO_M_Rural        .        LIGHTOIL   9.216
2050        .        NO_M_Rural        .        LIGHTOIL   9.133

2014        .        DK_CA_Kbh        .        ORIMULSION        1.542
2020        .        DK_CA_Kbh        .        ORIMULSION        1.492
2025        .        DK_CA_Kbh        .        ORIMULSION        1.328
2030        .        DK_CA_Kbh        .        ORIMULSION        1.165
2035        .        DK_CA_Kbh        .        ORIMULSION        1.095
2040        .        DK_CA_Kbh        .        ORIMULSION        1.025
2045        .        DK_CA_Kbh        .        ORIMULSION        1.002
2050        .        DK_CA_Kbh        .        ORIMULSION        0.979

2014        .        DK_CA_Kbh        .        PEAT   1.378
2020        .        DK_CA_Kbh        .        PEAT   0.823
2025        .        DK_CA_Kbh        .        PEAT   0.966
2030        .        DK_CA_Kbh        .        PEAT   1.108
2035        .        DK_CA_Kbh        .        PEAT   1.094
2040        .        DK_CA_Kbh        .        PEAT   1.080
2045        .        DK_CA_Kbh        .        PEAT   1.067
2050        .        DK_CA_Kbh        .        PEAT   1.053

2014        .        DK_CA_Kbh        .        MUNI_WASTE        0
2020        .        DK_CA_Kbh        .        MUNI_WASTE        0
2025        .        DK_CA_Kbh        .        MUNI_WASTE        0
2030        .        DK_CA_Kbh        .        MUNI_WASTE        0
2035        .        DK_CA_Kbh        .        MUNI_WASTE        0
2040        .        DK_CA_Kbh        .        MUNI_WASTE        0
2045        .        DK_CA_Kbh        .        MUNI_WASTE        0
2050        .        DK_CA_Kbh        .        MUNI_WASTE        0

2014        .        DK_CA_Kbh        .        STRAW     3.084
2020        .        DK_CA_Kbh        .        STRAW     3.068
2025        .        DK_CA_Kbh        .        STRAW     3.661
2030        .        DK_CA_Kbh        .        STRAW     4.253
2035        .        DK_CA_Kbh        .        STRAW     4.788
2040        .        DK_CA_Kbh        .        STRAW     5.323
2045        .        DK_CA_Kbh        .        STRAW     5.485
2050        .        DK_CA_Kbh        .        STRAW     5.647

2014        .        DK_CA_Kbh        .        WOOD     3.700
2020        .        DK_CA_Kbh        .        WOOD     3.707
2025        .        DK_CA_Kbh        .        WOOD     4.332
2030        .        DK_CA_Kbh        .        WOOD     4.958
2035        .        DK_CA_Kbh        .        WOOD     5.510
2040        .        DK_CA_Kbh        .        WOOD     6.062
2045        .        DK_CA_Kbh        .        WOOD     6.230
2050        .        DK_CA_Kbh        .        WOOD     6.397

2014        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2020        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2025        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2030        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2035        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2040        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2045        .        DK_CA_Kbh        .        WOOD_WASTE   0.386
2050        .        DK_CA_Kbh        .        WOOD_WASTE   0.386

2014        .        DK_CA_Kbh        .        WIND          0
2020        .        DK_CA_Kbh        .        WIND          0
2025        .        DK_CA_Kbh        .        WIND          0
2030        .        DK_CA_Kbh        .        WIND          0
2035        .        DK_CA_Kbh        .        WIND          0
2040        .        DK_CA_Kbh        .        WIND          0
2045        .        DK_CA_Kbh        .        WIND          0
2050        .        DK_CA_Kbh        .        WIND          0

2014        .        DK_CA_Kbh        .        SUN          0
2020        .        DK_CA_Kbh        .        SUN          0
2025        .        DK_CA_Kbh        .        SUN          0
2030        .        DK_CA_Kbh        .        SUN          0
2035        .        DK_CA_Kbh        .        SUN          0
2040        .        DK_CA_Kbh        .        SUN          0
2045        .        DK_CA_Kbh        .        SUN          0
2050        .        DK_CA_Kbh        .        SUN          0

2014        .        DK_CA_Kbh        .        ELECTRIC          0
2020        .        DK_CA_Kbh        .        ELECTRIC          0
2025        .        DK_CA_Kbh        .        ELECTRIC          0
2030        .        DK_CA_Kbh        .        ELECTRIC          0
2035        .        DK_CA_Kbh        .        ELECTRIC          0
2040        .        DK_CA_Kbh        .        ELECTRIC          0
2045        .        DK_CA_Kbh        .        ELECTRIC          0
2050        .        DK_CA_Kbh        .        ELECTRIC          0

2014        .        DK_CA_Kbh        .        WOOD_PELLETS     5.175
2020        .        DK_CA_Kbh        .        WOOD_PELLETS     5.136
2025        .        DK_CA_Kbh        .        WOOD_PELLETS     5.732
2030        .        DK_CA_Kbh        .        WOOD_PELLETS     6.327
2035        .        DK_CA_Kbh        .        WOOD_PELLETS     6.860
2040        .        DK_CA_Kbh        .        WOOD_PELLETS     7.392
2045        .        DK_CA_Kbh        .        WOOD_PELLETS     7.555
2050        .        DK_CA_Kbh        .        WOOD_PELLETS     7.719


2014        .        DK_CA_Kbh        .        BIOGAS        0
2020        .        DK_CA_Kbh        .        BIOGAS        0
2025        .        DK_CA_Kbh        .        BIOGAS        0
2030        .        DK_CA_Kbh        .        BIOGAS        0
2035        .        DK_CA_Kbh        .        BIOGAS        0
2040        .        DK_CA_Kbh        .        BIOGAS        0
2045        .        DK_CA_Kbh        .        BIOGAS        0
2050        .        DK_CA_Kbh        .        BIOGAS        0

2014        .        DK_CA_Kbh        .        BIOGAS_net     11.2828
2020        .        DK_CA_Kbh        .        BIOGAS_net     11.2828
2025        .        DK_CA_Kbh        .        BIOGAS_net     11.2908
2030        .        DK_CA_Kbh        .        BIOGAS_net     11.2908
2035        .        DK_CA_Kbh        .        BIOGAS_net     11.2908
2040        .        DK_CA_Kbh        .        BIOGAS_net     11.2908
2045        .        DK_CA_Kbh        .        BIOGAS_net     11.2908
2050        .        DK_CA_Kbh        .        BIOGAS_net     11.2908

2014        .        DK_CA_Kbh        .        BIOGAS_EC       0
2020        .        DK_CA_Kbh        .        BIOGAS_EC       0
2025        .        DK_CA_Kbh        .        BIOGAS_EC       0
2030        .        DK_CA_Kbh        .        BIOGAS_EC       0
2035        .        DK_CA_Kbh        .        BIOGAS_EC       0
2040        .        DK_CA_Kbh        .        BIOGAS_EC       0
2045        .        DK_CA_Kbh        .        BIOGAS_EC       0
2050        .        DK_CA_Kbh        .        BIOGAS_EC       0

2014        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.110
2020        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.198
2025        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.329
2030        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.450
2035        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.499
2040        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.547
2045        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.573
2050        .        DK_CA_Kbh        .        BIOGAS_EC_net        13.600

2014        .        DK_CA_Kbh        .        SURPLUS_H          0
2020        .        DK_CA_Kbh        .        SURPLUS_H          0
2025        .        DK_CA_Kbh        .        SURPLUS_H          0
2030        .        DK_CA_Kbh        .        SURPLUS_H          0
2035        .        DK_CA_Kbh        .        SURPLUS_H          0
2040        .        DK_CA_Kbh        .        SURPLUS_H          0
2045        .        DK_CA_Kbh        .        SURPLUS_H          0
2050        .        DK_CA_Kbh        .        SURPLUS_H          0

2014        .        DK_CA_Kbh        .        WAVE          0
2020        .        DK_CA_Kbh        .        WAVE          0
2025        .        DK_CA_Kbh        .        WAVE          0
2030        .        DK_CA_Kbh        .        WAVE          0
2035        .        DK_CA_Kbh        .        WAVE          0
2040        .        DK_CA_Kbh        .        WAVE          0
2045        .        DK_CA_Kbh        .        WAVE          0
2050        .        DK_CA_Kbh        .        WAVE          0

2014        .        DK_CA_Kbh        .        GeoEL          0
2020        .        DK_CA_Kbh        .        GeoEL          0
2025        .        DK_CA_Kbh        .        GeoEL          0
2030        .        DK_CA_Kbh        .        GeoEL          0
2035        .        DK_CA_Kbh        .        GeoEL          0
2040        .        DK_CA_Kbh        .        GeoEL          0
2045        .        DK_CA_Kbh        .        GeoEL          0
2050        .        DK_CA_Kbh        .        GeoEL          0

2014        .        DK_CA_Kbh        .        BIOOIL         18.109
2020        .        DK_CA_Kbh        .        BIOOIL         18.039
2025        .        DK_CA_Kbh        .        BIOOIL         19.106
2030        .        DK_CA_Kbh        .        BIOOIL         20.172
2035        .        DK_CA_Kbh        .        BIOOIL         21.125
2040        .        DK_CA_Kbh        .        BIOOIL         22.078
2045        .        DK_CA_Kbh        .        BIOOIL         22.371
2050        .        DK_CA_Kbh        .        BIOOIL         22.663

2014        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2020        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2025        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2030        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2035        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2040        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2045        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0
2050        .        DK_CA_Kbh        .        HAZARDOUSWASTE          0

/;

FUELPRICE(Y,IA,'NAT_GAS')$(ICA('NORWAY',IA) AND (FUELPRICE(Y,IA,'NAT_GAS') EQ 0))=FUELPRICE(Y,'NO_M_Rural','NAT_GAS');
FUELPRICE(Y,IA,'NAT_GAS')$(ICA('GERMANY',IA) AND (FUELPRICE(Y,IA,'NAT_GAS') EQ 0))=FUELPRICE(Y,'DE_CS_A1','NAT_GAS');
FUELPRICE(Y,IA,'NAT_GAS')$(ICA('FINLAND',IA) AND (FUELPRICE(Y,IA,'NAT_GAS') EQ 0))=FUELPRICE(Y,'FI_R_Urban','NAT_GAS');
FUELPRICE(Y,IA,'NAT_GAS')$(ICA('SWEDEN',IA) AND (FUELPRICE(Y,IA,'NAT_GAS') EQ 0))=1.1*FUELPRICE(Y,'SE_M_Urban','NAT_GAS');

FUELPRICE(Y,IA,'NG_CCS')$(FUELPRICE(Y,IA,'NAT_GAS'))=FUELPRICE(Y,IA,'NAT_GAS');
FUELPRICE(Y,IA,'LIGNITE')$(FUELPRICE(Y,IA,'COAL'))=0.5*FUELPRICE(Y,IA,'COAL');
FUELPRICE(Y,IA,'WP_CCS')$(FUELPRICE(Y,IA,'WOOD_PELLETS'))=FUELPRICE(Y,IA,'WOOD_PELLETS');
FUELPRICE(Y,IA,'COAL_CCS')$(FUELPRICE(Y,IA,'COAL'))=FUELPRICE(Y,IA,'COAL');

FUELPRICE(Y,IA,'LIGHTOIL')$((NOT (ICA('DENMARK',IA))) AND (FUELPRICE(Y,IA,'LIGHTOIL') EQ 0))=FUELPRICE(Y,'NO_M_Rural','LIGHTOIL');

FUELPRICE(Y,'DK_E_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');
FUELPRICE(Y,'DK_W_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');
FUELPRICE(Y,'FI_R_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');
FUELPRICE(Y,'SE_M_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');
FUELPRICE(Y,'SE_N_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');
FUELPRICE(Y,'SE_S_Rural','STRAW')$(FUELPRICE(Y,'DK_CA_Kbh','STRAW'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','STRAW');

FUELPRICE(Y,'DK_E_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');
FUELPRICE(Y,'DK_W_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');
FUELPRICE(Y,'FI_R_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');
FUELPRICE(Y,'SE_M_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');
FUELPRICE(Y,'SE_N_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');
FUELPRICE(Y,'SE_S_Rural','WOOD_WASTE')$(FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE'))=0.85*FUELPRICE(Y,'DK_CA_Kbh','WOOD_WASTE');

*Unless other values are assigned in the TABLE FUELPRICE above,
*the values for 'DK_CA_Kbh' are used for all A:
FUELPRICE(Y,IA,FFF)$((FUELPRICE(Y,IA,FFF) EQ 0) AND
((SUM(G$(GDATA(G,'GDFUEL') EQ FDATA(FFF,'FDACRONYM')),GKFX(Y,IA,G)))OR (SUM(G$(GDATA(G,'GDFUEL') EQ FDATA(FFF,'FDACRONYM')),AGKN(IA,G)))))
=FUELPRICE(Y,'DK_CA_Kbh',FFF);





































