Parameter GMAXFCOMB(YYY,CCCRRRAAA,IF1,IF2) Maximum fuel use (GJ) per year

/
2020    .    GERMANY    .    COAL    .    LIGNITE              8.28E+08
2025    .    GERMANY    .    COAL    .    LIGNITE              7.00E+08
2030    .    GERMANY    .    COAL    .    LIGNITE              5.00E+08
2035    .    GERMANY    .    COAL    .    LIGNITE              1.70E+07
2040    .    GERMANY    .    COAL    .    LIGNITE              1.50E+07
2045    .    GERMANY    .    COAL    .    LIGNITE              1.00E+07
2050    .    GERMANY    .    COAL    .    LIGNITE              8.00E+06

2020    .    FINLAND    .    COAL    .    PEAT                 1.77E+08
2025    .    FINLAND    .    COAL    .    PEAT                 1.52E+08
2030    .    FINLAND    .    COAL    .    PEAT                 8.70E+07

2020    .    SWEDEN    .    COAL    .    PEAT                  1.00E+07
2025    .    SWEDEN    .    COAL    .    PEAT                  1.00E+07
2030    .    SWEDEN    .    COAL    .    PEAT                  5.00E+06


2020    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.80E+07
2025    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.80E+07
2030    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.80E+07
2035    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.00E+07
2040    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.00E+07
2045    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.00E+07
2050    .    GERMANY    .    LIGHTOIL    .    FUELOIL          1.00E+07

2020    .    DENMARK    .    LIGHTOIL    .    FUELOIL          1.00E+06
2025    .    DENMARK    .    LIGHTOIL    .    FUELOIL          1.00E+06

2020    .    NORWAY    .    LIGHTOIL    .    FUELOIL           2.00E+06
2025    .    NORWAY    .    LIGHTOIL    .    FUELOIL           2.00E+06
2030    .    NORWAY    .    LIGHTOIL    .    FUELOIL           2.00E+06

2020    .    SWEDEN    .    LIGHTOIL    .    FUELOIL           3.00E+07
2025    .    SWEDEN    .    LIGHTOIL    .    FUELOIL           1.50E+07
2030    .    SWEDEN    .    LIGHTOIL    .    FUELOIL           1.00E+06

2020    .    FINLAND    .    LIGHTOIL    .    FUELOIL          2.50E+07
2025    .    FINLAND    .    LIGHTOIL    .    FUELOIL          1.70E+07



/;