*Last time modified (Raffaele, 16-06-2015)
PARAMETER INSCAPHP(YYY,C) 'Maximum heat pumps installed capacity in the scenario (MW)'

/


$ontext

2025       . SWEDEN                     eps
2025       . NORWAY                     eps
2025       . FINLAND                    eps
2025       . GERMANY                    eps

2035       . SWEDEN                     eps
2035       . NORWAY                     eps
2035       . FINLAND                    eps
2035       . GERMANY                    eps

2050       . SWEDEN                     eps
2050       . NORWAY                     eps
2050       . FINLAND                    eps
2050       . GERMANY                    eps

$offtext
/;
