*Last time modified (Raffaele, 16-06-2015)
*Data for Sweden, Norway and Finland are taken from NETP (in case no data were available a linear trend was assumed)
*Data for Denmark are taken from the DEA energy scenario report (2035 and 2050), while for the year 2012 data are taken from energy statistics 2013 by DEA
*again for 2025 a linear trend is assumed between 2012 and 2035

PARAMETER INSCAPWINDOFF(YYY,C) 'Maximum OFFSHORE wind POWER installed capacity in the scenario (MW)'

/
2020   .    DENMARK     20196
2020   .    NORWAY      8543
2020   .    SWEDEN      4191
*2020   .    FINLAND     3511
2020   .    GERMANY     9633

2025   .    DENMARK     35968
2025   .    NORWAY      15662
2025   .    SWEDEN      7621
*2025   .    FINLAND     6438
2025   .    GERMANY     17535

2030   .    DENMARK     51739
2030   .    NORWAY      22781
2030   .    SWEDEN      11050
*2030   .    FINLAND     9364
2030   .    GERMANY     25438

2035   .    DENMARK     67510
2035   .    NORWAY      29900
2035   .    SWEDEN      14480
*2035   .    FINLAND     12290
2035   .    GERMANY     33340

2040   .    DENMARK     89340
2040   .    NORWAY      49833
2040   .    SWEDEN      23987
*2040   .    FINLAND     19727
2040   .    GERMANY     47193

2045   .    DENMARK     111170
2045   .    NORWAY      69767
2045   .    SWEDEN      33493
*2045   .    FINLAND     27163
2045   .    GERMANY     61047

2050   .    DENMARK     133000
2050   .    NORWAY      89700
2050   .    SWEDEN      43000
*2050   .    FINLAND     34600
2050   .    GERMANY     74900


/;
