*Last time modified (Raffaele, 16-06-2015)
*Data for Sweden, Norway and Finland are taken from the NETP (in case no data were available a linear trend was assumed)
*Data for Denmark are taken from the DEA energy scenario report (2035 and 2050), while for the year 2012 data are taken from energy statistics 2013 by DEA
*again for 2025 a linear trend is assumed between 2012 and 2035

PARAMETER INSCAPWINDON(YYY,CCCRRRAAA) 'Maximum ONSHORE wind POWER installed capacity in the scenario (MW)'

/
2020   .    DK_E          720
2020   .    DK_W          3407
2020   .    NORWAY        2813
2020   .    SWEDEN        5746
2020   .    FINLAND       2401
2020   .    GERMANY       40824

2025   .    DK_E          854
2025   .    DK_W          3821
2025   .    NORWAY        4799
2025   .    SWEDEN        10534
2025   .    FINLAND       4368
2025   .    GERMANY       51906

2030   .    DK_E          987
2030   .    DK_W          4236
2030   .    NORWAY        6784
2030   .    SWEDEN        15322
2030   .    FINLAND       6334
2030   .    GERMANY       62988

2035   .    DK_E          1120
2035   .    DK_W          4650
2035   .    NORWAY        8770
2035   .    SWEDEN        20110
2035   .    FINLAND       8300
2035   .    GERMANY       74070

2040   .    DK_E          1253
2040   .    DK_W          5260
2040   .    NORWAY        10513
2040   .    SWEDEN        25073
2040   .    FINLAND       10533
2040   .    GERMANY       82263

2045   .    DK_E          1387
2045   .    DK_W          5870
2045   .    NORWAY        12257
2045   .    SWEDEN        30037
2045   .    FINLAND       12767
2045   .    GERMANY       90457

2050   .    DK_E          1520
2050   .    DK_W          6480
2050   .    NORWAY        14000
2050   .    SWEDEN        35000
2050   .    FINLAND       15000
2050   .    GERMANY       98650

/;
