PARAMETER  scen_Delta_H(AAA,SSS,TTT,scenarios_H)  "Scenarios for calculation of marginal values of electricity"
/

DK_CA_Aab                       .    S01    .    T001 .        DK_CA_Aab_scenH                  1.797
DK_CA_Aab_DEC                   .    S01    .    T001 .        DK_CA_Aab_DEC_scenH              0.959
DK_CA_Aal                       .    S01    .    T001 .        DK_CA_Aal_scenH                  5.000
DK_CA_Aal_DEC                   .    S01    .    T001 .        DK_CA_Aal_DEC_scenH              4.460
DK_CA_Aarhus                    .    S01    .    T001 .        DK_CA_Aarhus_scenH               5.000
DK_CA_Aarhus_DEC                .    S01    .    T001 .        DK_CA_Aarhus_DEC_scenH           3.873
DK_CA_Esb                       .    S01    .    T001 .        DK_CA_Esb_scenH                  5.000
DK_CA_Esb_DEC                   .    S01    .    T001 .        DK_CA_Esb_DEC_scenH              0.647
DK_CA_Hern                      .    S01    .    T001 .        DK_CA_Hern_scenH                 4.559
DK_CA_Hern_DEC                  .    S01    .    T001 .        DK_CA_Hern_DEC_scenH             4.015
DK_CA_Kal                       .    S01    .    T001 .        DK_CA_Kal_scenH                  2.091
DK_CA_Kal_DEC                   .    S01    .    T001 .        DK_CA_Kal_DEC_scenH              0.728
DK_CA_KBH                       .    S01    .    T001 .        DK_CA_KBH_scenH                  5.000
DK_CA_KBH_DEC                   .    S01    .    T001 .        DK_CA_KBH_DEC_scenH              0.728
DK_CA_Odense                    .    S01    .    T001 .        DK_CA_Odense_scenH               5.000
DK_CA_Odense_DEC                .    S01    .    T001 .        DK_CA_Odense_DEC_scenH           2.568
DK_CA_Randers                   .    S01    .    T001 .        DK_CA_Randers_scenH              3.212
DK_CA_Randers_DEC               .    S01    .    T001 .        DK_CA_Randers_DEC_scenH          0.719
DK_CA_Roenne                    .    S01    .    T001 .        DK_CA_Roenne_scenH               0.065
DK_CA_Roenne_DEC                .    S01    .    T001 .        DK_CA_Roenne_DEC_scenH           0.631
DK_CA_TVIS                      .    S01    .    T001 .        DK_CA_TVIS_scenH                 5.000
DK_CA_TVIS_DEC                  .    S01    .    T001 .        DK_CA_TVIS_DEC_scenH             1.905
DK_CA_Vestfrb_DEC               .    S01    .    T001 .        DK_CA_Vestfrb_DEC_scenH          0.090
DK_E_DTU                        .    S01    .    T001 .        DK_E_DTU_scenH                   0.324
DK_MA_Grenaa                    .    S01    .    T001 .        DK_MA_Grenaa_scenH               1.648
DK_MA_Grenaa_DEC                .    S01    .    T001 .        DK_MA_Grenaa_DEC_scenH           0.311
DK_MA_Hil                       .    S01    .    T001 .        DK_MA_Hil_scenH                  1.223
DK_MA_Hil_DEC                   .    S01    .    T001 .        DK_MA_Hil_DEC_scenH              0.855
DK_MA_Hjoerring                 .    S01    .    T001 .        DK_MA_Hjoerring_scenH            1.996
DK_MA_Holst                     .    S01    .    T001 .        DK_MA_Holst_scenH                2.977
DK_MA_Holst_DEC                 .    S01    .    T001 .        DK_MA_Holst_DEC_scenH            2.541
DK_MA_Horsens                   .    S01    .    T001 .        DK_MA_Horsens_scenH              1.607
DK_MA_Horsens_DEC               .    S01    .    T001 .        DK_MA_Horsens_DEC_scenH          0.542
DK_MA_NrdOstSj                  .    S01    .    T001 .        DK_MA_NrdOstSj_scenH             1.500
DK_MA_NrdOstSj_DEC              .    S01    .    T001 .        DK_MA_NrdOstSj_DEC_scenH         0.014
DK_MA_Silk                      .    S01    .    T001 .        DK_MA_Silk_scenH                 2.136
DK_MA_Sndborg                   .    S01    .    T001 .        DK_MA_Sndborg_scenH              1.736
DK_MA_Sndborg_DEC               .    S01    .    T001 .        DK_MA_Sndborg_DEC_scenH          0.623
DK_MA_Viborg                    .    S01    .    T001 .        DK_MA_Viborg_scenH               1.986
DK_MA_Viborg_DEC                .    S01    .    T001 .        DK_MA_Viborg_DEC_scenH           1.748
DK_MAM_Aars                     .    S01    .    T001 .        DK_MAM_Aars_scenH                0.602
DK_MAM_Aars_DEC                 .    S01    .    T001 .        DK_MAM_Aars_DEC_scenH            1.091
DK_MAM_Frdhavn                  .    S01    .    T001 .        DK_MAM_Frdhavn_scenH             1.186
DK_MAM_Frdhavn_DEC              .    S01    .    T001 .        DK_MAM_Frdhavn_DEC_scenH         0.970
DK_MAM_Had                      .    S01    .    T001 .        DK_MAM_Had_scenH                 0.875
DK_MAM_Had_DEC                  .    S01    .    T001 .        DK_MAM_Had_DEC_scenH             1.605
DK_MAM_Hammel                   .    S01    .    T001 .        DK_MAM_Hammel_scenH              0.502
DK_MAM_Hammel_DEC               .    S01    .    T001 .        DK_MAM_Hammel_DEC_scenH          0.722
DK_MAM_Hobro                    .    S01    .    T001 .        DK_MAM_Hobro_scenH               0.355
DK_MAM_Hobro_DEC                .    S01    .    T001 .        DK_MAM_Hobro_DEC_scenH           0.782
DK_MAM_Naestved                 .    S01    .    T001 .        DK_MAM_Naestved_scenH            0.697
DK_MAM_Naestved_DEC             .    S01    .    T001 .        DK_MAM_Naestved_DEC_scenH        1.075
DK_MAM_NrAlslev                 .    S01    .    T001 .        DK_MAM_NrAlslev_scenH            0.063
DK_MAM_Nyborg                   .    S01    .    T001 .        DK_MAM_Nyborg_scenH              1.104
DK_MAM_Nyk                      .    S01    .    T001 .        DK_MAM_Nyk_scenH                 0.747
DK_MAM_Nyk_DEC                  .    S01    .    T001 .        DK_MAM_Nyk_DEC_scenH             1.234
DK_MAM_Skagen                   .    S01    .    T001 .        DK_MAM_Skagen_scenH              0.443
DK_MAM_Slagelse                 .    S01    .    T001 .        DK_MAM_Slagelse_scenH            0.480
DK_MAM_Slagelse_DEC             .    S01    .    T001 .        DK_MAM_Slagelse_DEC_scenH        0.273
DK_MAM_Svend                    .    S01    .    T001 .        DK_MAM_Svend_scenH               1.021
DK_MAM_Svend_DEC                .    S01    .    T001 .        DK_MAM_Svend_DEC_scenH           0.958
DK_MAM_Thisted                  .    S01    .    T001 .        DK_MAM_Thisted_scenH             1.195
DK_MAM_Thisted_DEC              .    S01    .    T001 .        DK_MAM_Thisted_DEC_scenH         1.078


/
;
scen_Delta_H(IA,S,T,'BASE')=EPS;

scen_Delta_H(IA,S,T,scenarios_H)$(scen_Delta_H(IA,'S01','T001',scenarios_H) AND MAR_H_S(S))=scen_Delta_H(IA,'S01','T001',scenarios_H);


