PARAMETER  TAX_DH(CCC) "Consumers tax on heat consumption (Money/MWh)"
/
DENMARK                                                   0.0000
ESTONIA                                                   0.0000
FINLAND                                                   0.0000
GERMANY                                                   0.0000
LATVIA                                                    0.0000
LITHUANIA                                                 0.0000
NORWAY                                                    0.0000
POLAND                                                    0.0000
RUSSIA                                                    0.0000
SWEDEN                                                    0.0000
BELARUS                                                   0.0000
/;
