PARAMETER TECH_CO2(TECHTYPE) 'Marginal emissions per type of technology (kg CO2/MWh)'

/
"Biodiesel Boiler"                           0.00
"Biodiesel Condensing"                       0.00
"Biogas Backpressure"                        -278.64
"Biogas Boiler"                              -278.64
"Biogas Condensing"                          -278.64
"Biogas Extraction"                          -278.64
"Biomethane Backpressure"                    -278.64
"Biomethane Condensing"                      -278.64
"Biomethane Extraction"                      -278.64
"Coal Backpressure"                          342.00
"Coal Boiler"                                342.00
"Coal CCS Condensing"                        34.20
"Coal CCS Extraction"                        34.20
"Coal Condensing"                            342.00
"Coal Extraction"                            342.00
"Diesel Backpressure"                        266.40
"Diesel Boiler"                              266.40
"Diesel Condensing"                          266.40
"Dummy"                                      0.00
"Electricity Storage"                        0.00
"Electricity to Heat"                        0.00
"Electricity to Hydrogen"                    0.00
"Fueloil Backpressure"                       280.80
"Fueloil Boiler"                             280.80
"Fueloil Condensing"                         280.80
"Fueloil Extraction"                         280.80
"Geothermal Condensing"                      0.00
"Geothermal Heating"                         0.00
"H2 Storage"                                 0.00
"Hazardous Waste"                            0.00
"Heat Storage"                               0.00
"Heat_23?"                                   0.00
"Hydropower Run-of-River"                    0.00
"Hydropower"                                 0.00
"MSW Backpressure"                           116.86
"MSW Boiler"                                 116.86
"MSW Condensing"                             116.86
"MSW Extraction"                             116.86
"Natural Gas Backpressure"                   204.48
"Natural Gas Boiler"                         204.48
"Natural Gas CCS Condensing"                 30.96
"Natural Gas CCS Extraction"                 30.96
"Natural Gas Condensing"                     204.48
"Natural Gas Extraction"                     204.48
"Nuclear"                                    0.00
"Peat Backpressure"                          385.20
"Peat Boiler"                                385.20
"Peat Condensing"                            385.20
"Peat Extraction"                            385.20
"Straw Backpressure"                         39.60
"Shale Condensing"                           381.60
"Shale Extraction"                           381.60
"Solar PV"                                   0.00
"Straw Boiler"                               39.60
"Straw Extraction"                           39.60
"Straw Pellets Backpresssure"                39.60
"Surplus Heat"                               0.00
"Thermal Solar"                              0.00
"Wave"                                       0.00
"Wind"                                       0.00
"Wood Backpressure"                          0.00
"Wood Boiler"                                0.00
"Wood Condensing"                            0.00
"Wood Extraction"                            0.00
"Wood Pellets Backpressure"                  3.60
"Wood Pellets Boiler"                        3.60
"Wood Pellets CCS Condensing"                -287.10
"Wood Pellets CCS Extraction"                -287.10
"Wood Pellets Condensing"                     3.60
"Wood Pellets Extraction"                    3.60
"Wood Waste Backpressure"                    0.00
"Wood Waste Boiler"                          0.00
"Wood Waste Condensing"                      0.00
"Wood Waste Extraction"                      0.00
/
;





