*Last time modified (Davide, 10-05-2015)

PARAMETER XINVCOST(IRRRE,IRRRI) "Investment cost in new transmission capacity (Money/MW)"
/
DE_CS    .       DE_NE        291046
DE_CS    .       DE_NW        337613

DE_NE    .       DE_NW        267762
DE_NE    .       DK_E         279404
DE_NE    .       SE_S         430748

DE_NW    .       DK_W         337613
DE_NW    .       NO_S         704331
DE_NW    .       SE_S         500599

DK_E    .        DK_W         302688
DK_E    .        SE_S         250299

DK_W    .        NO_S         413285
DK_W    .        SE_M         459852

FI_R    .        NO_N         337613
FI_R    .        SE_M         471494
FI_R    .        SE_N         337613

NO_M    .        NO_N         337613
NO_M    .        NO_S         337613
NO_M    .        SE_N         337613

NO_N    .        SE_N         305598

NO_O    .        NO_S         302688
NO_O    .        SE_M         337613

SE_M    .        SE_N         337613
SE_M    .        SE_S         337613

/;
