*Paremter introduced by Amalia, to take into account the technical lifetime of new investments in transmission capacity

PARAMETER XLIFETIME(IRRRE,IRRRI) "Technical lifetime of investments in new transmission capacity (year)"

/
DE_CS    .       DE_NE   40
DE_CS    .       DE_NW   40

DE_NE    .       DE_NW   40
DE_NE    .       DK_E    40
DE_NE    .       SE_S    40

DE_NW    .       DK_W    40
DE_NW    .       NO_S    40
DE_NW    .       SE_S    40

DK_E    .        DE_NE   40
DK_E    .        DK_W    40
DK_E    .        SE_S    40

DK_W    .        NO_S    40
DK_W    .        SE_M    40

FI_R    .        NO_N    40
FI_R    .        SE_M    40
FI_R    .        SE_N    40

NO_M    .        NO_N    40
NO_M    .        NO_S    40
NO_M    .        SE_N    40

NO_N    .        SE_N    40

NO_O    .        NO_S    40
NO_O    .        SE_M    40

SE_M    .        SE_N    40
SE_M    .        SE_S    40

/;
