SET AAAOPTIFLOW(AAA)     'Areas that are used in the OptiFLow calculations'
*Add the area Vestfrb in Balmorel, as the DH is connected with the DH of main COpenhagen, or should we join the are to KBH? I vote for joining, we decrease one area :), which is good

/
DK_CA_Aab
DK_CA_Aal
DK_CA_Aarhus
DK_CA_Esb
DK_CA_Hern
DK_CA_Kal
DK_CA_KBH
DK_CA_Odense
DK_CA_Randers
DK_CA_Roenne
DK_CA_TVIS
*DK_CA_Vestfrb
DK_E_DTU
DK_MA_Grenaa
DK_MA_Hil
DK_MA_Hjoerring
DK_MA_Holst
DK_MA_Horsens
DK_MA_NrdOstSj
DK_MA_Silk
DK_MA_Sndborg
DK_MA_Viborg
DK_MAM_Aars
DK_MAM_Frdhavn
DK_MAM_Had
DK_MAM_Hammel
DK_MAM_Hobro
DK_MAM_Naestved
DK_MAM_NrAlslev
DK_MAM_Nyborg
DK_MAM_Nyk
DK_MAM_Skagen
DK_MAM_Slagelse
DK_MAM_Svend
DK_MAM_Thisted



Aabenraa
Aalborg
Aarhus
Aeroe
Albertslund
Alleroed
Assens
Ballerup
Billund
Bornholm
Broendby
Broenderslev
Christiansoe
Dragoer
Egedal
Esbjerg
Faaborg-Midtfyn
Fanoe
Favrskov
Faxe
Fredensborg
Fredericia
Frederiksberg
Frederikshavn
Frederikssund
Furesoe
Gentofte
Gladsaxe
Glostrup
Greve
Gribskov
Guldborgsund
Haderslev
Halsnaes
Hedensted
Helsingoer
Herlev
Herning
Hilleroed
Hjoerring
Hoeje_Taastrup
Hoersholm
Holbaek
Holstebro
Horsens
Hvidovre
Ikast-Brande
Ishoej
Jammerbugt
Kalundborg
Kerteminde
Koebenhavn
Koege
Kolding
Laesoe
Langeland
Lejre
Lemvig
Lolland
Lyngby-Taarbaek
Mariagerfjord
Middelfart
Morsoe
Naestved
Norddjurs
Nordfyns
Nyborg
Odder
Odense
Odsherred
Randers
Rebild
Ringkoebing-Skjern
Ringsted
Roedovre
Roskilde
Rudersdal
Samsoe
Silkeborg
Skanderborg
Skive
Slagelse
Soenderborg
Solroed
Soroe
Stevns
Struer
Svendborg
Syddjurs
Taarnby
Thisted
Toender
Vallensbaek
Varde
Vejen
Vejle
Vesthimmerlands
Viborg
Vordingborg





UK_AAA





/;
