SET APKNDISC_AP(AAA,PROC) "Areas for possible location of discrete capacity investments in Processes (addon apkndisc)"
/





$ontext

DK_CA_KBH.WasteincinCHP_35
*DK_FYN_Odense.BiogasCHP   later
*DK_FYN_Odense.Boiler-WO   later
DK_CA_KBH.Engine-NG

$offtext

/;
/*

/*The above data for test only.
Based on  Continuous investments:
                    WasteincinCHP_35   BiogasCHP   Boiler-WO    Engine-NG
2010.DK_CA_KBH          3601.640        137.233     423.781     423.781

*/
