PARAMETER EQFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"
/

*2050   . DENMARK  .  Passenger_RE_fuels_Buffer     .  PASSENGER_RE_FUELS_FLOW       2.5E7

*2050   . DENMARK  .  Freight_RE_fuels_Buffer       .  FREIGHT_RE_FUELS_FLOW         1.501E7
*2050   . DENMARK  .  BioJetBuffer                  .  BIOJETFLOW                   3.595E7

*2050   . DENMARK  .  ElectroBuffer                 .  ELCOST_FLOW                  100
/;




