PARAMETER MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"
/


2050   . DENMARK  .      GasBuffer         	   .   GASFLOW                      25E6

*2050   . DENMARK  .  Passenger_RE_fuels_Buffer     .  PASSENGER_RE_FUELS_FLOW       2.5E7
*2050   . DENMARK  .  Freight_RE_fuels_Buffer       .  FREIGHT_RE_FUELS_FLOW         3E7
*2050   . DENMARK  .  BioJetBuffer                  .  BIOJETFLOW                    5.766E7

2050   . DENMARK  .  SeaBuffer     		.  SEAFLOW       		10E6
2050   . DENMARK  .  RoadBuffer       		.  ROADFLOW         		80E6
2050   . DENMARK  .  AirBuffer                  .  AIRFLOW                    	58E6


/;




