SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/
CO2_Source_PH
CO2_Source_IND
CO2_Source_DAC



$ontext

Wood_Source
Straw_Source
Muni_Waste_Source
Wood_Pellets_Source
Manure_Source
Deep_Litter_Source
Food_Waste_Source
Nature_Area_Source
Other_Gas_Source

$offtext



Wood_Gen
Straw_Gen
Muni_Waste_Gen
Wood_Pellets_Gen
Manure_Gen
Deep_Litter_Gen
Food_Waste_Gen
Nature_Area_Gen


Other_Gas_Gen

BioLiquid_Import

/;
