SET AAAOPTIFLOW(AAA)     'Areas that are used in the OptiFLow calculations'
*Add the area Vestfrb in Balmorel, as the DH is connected with the DH of main COpenhagen, or should we join the are to KBH? I vote for joining, we decrease one area :), which is good

/
DK_CA_Aab
DK_CA_Aal
DK_CA_Aarhus
DK_CA_Esb
DK_CA_Hern
DK_CA_Kal
DK_CA_KBH
DK_CA_Odense
DK_CA_Randers
DK_CA_Roenne
DK_CA_TVIS
*DK_CA_Vestfrb
DK_E_DTU
DK_MA_Grenaa
DK_MA_Hil
DK_MA_Hjoerring
DK_MA_Holst
DK_MA_Horsens
DK_MA_NrdOstSj
DK_MA_Silk
DK_MA_Sndborg
DK_MA_Viborg
DK_MAM_Aars
DK_MAM_Frdhavn
DK_MAM_Had
DK_MAM_Hammel
DK_MAM_Hobro
DK_MAM_Naestved
DK_MAM_NrAlslev
DK_MAM_Nyborg
DK_MAM_Nyk
DK_MAM_Skagen
DK_MAM_Slagelse
DK_MAM_Svend
DK_MAM_Thisted

UK_AAA
/;
