PARAMETER MAXFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"
/


2050    .       DK_CA_Aab       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           132985
2050    .       DK_CA_Aal       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           531941
2050    .       DK_CA_Aarhus    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           519395
2050    .       DK_CA_Esb       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           22582
2050    .       DK_CA_Hern      .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           403974
2050    .       DK_CA_Kal       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           649871
2050    .       DK_CA_KBH       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           642344
2050    .       DK_CA_Odense    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           727655
2050    .       DK_CA_Randers   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           240879
2050    .       DK_CA_Roenne    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           195714
2050    .       DK_CA_TVIS      .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           589651
2050    .       DK_CA_Vestfrb   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           25092
2050    .       DK_E_DTU        .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           193205
2050    .       DK_MA_Grenaa    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           72765
2050    .       DK_MA_Hil       .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           153058
2050    .       DK_MA_Hjoerring .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           426556
2050    .       DK_MA_Holst     .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           338736
2050    .       DK_MA_Horsens   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           EPS
2050    .       DK_MA_NrdOstSj  .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           95348
2050    .       DK_MA_Silk      .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           205751
2050    .       DK_MA_Sndborg   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           85311
2050    .       DK_MA_Viborg    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           65238
2050    .       DK_MAM_Aars     .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           117930
2050    .       DK_MAM_Frdhavn  .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           208260
2050    .       DK_MAM_Had      .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           183168
2050    .       DK_MAM_Hammel   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           143022
2050    .       DK_MAM_Hobro    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           476739
2050    .       DK_MAM_Naestved .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           EPS
2050    .       DK_MAM_NrAlslev .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           125458
2050    .       DK_MAM_Nyborg   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           745219
2050    .       DK_MAM_Nyk      .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           EPS
2050    .       DK_MAM_Skagen   .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           240879
2050    .       DK_MAM_Slagelse .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           240879
2050    .       DK_MAM_Svend    .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           273498
2050    .       DK_MAM_Thisted  .       STRAW_GEN       .       STRAW_GEN_FLOW                                                           EPS




2050    .       DK_CA_Aab       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            36824
2050    .       DK_CA_Aal       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            147295
2050    .       DK_CA_Aarhus    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            143821
2050    .       DK_CA_Esb       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            6253
2050    .       DK_CA_Hern      .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            111861
2050    .       DK_CA_Kal       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            179950
2050    .       DK_CA_KBH       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            177865
2050    .       DK_CA_Odense    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            201488
2050    .       DK_CA_Randers   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            66699
2050    .       DK_CA_Roenne    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            54193
2050    .       DK_CA_TVIS      .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            163275
2050    .       DK_CA_Vestfrb   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            6948
2050    .       DK_E_DTU        .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            53499
2050    .       DK_MA_Grenaa    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            20149
2050    .       DK_MA_Hil       .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            42382
2050    .       DK_MA_Hjoerring .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            118114
2050    .       DK_MA_Holst     .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            93796
2050    .       DK_MA_Horsens   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            EPS
2050    .       DK_MA_NrdOstSj  .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            26402
2050    .       DK_MA_Silk      .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            56972
2050    .       DK_MA_Sndborg   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            23623
2050    .       DK_MA_Viborg    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            18064
2050    .       DK_MAM_Aars     .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            32655
2050    .       DK_MAM_Frdhavn  .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            57667
2050    .       DK_MAM_Had      .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            50719
2050    .       DK_MAM_Hammel   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            39603
2050    .       DK_MAM_Hobro    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            132009
2050    .       DK_MAM_Naestved .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            EPS
2050    .       DK_MAM_NrAlslev .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            34739
2050    .       DK_MAM_Nyborg   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            206351
2050    .       DK_MAM_Nyk      .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            EPS
2050    .       DK_MAM_Skagen   .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            66699
2050    .       DK_MAM_Slagelse .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            66699
2050    .       DK_MAM_Svend    .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            75732
2050    .       DK_MAM_Thisted  .       WOOD_GEN        .       WOOD_GEN_FLOW                                                            EPS




2050    .       DK_CA_Aab       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_CA_Aal       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Aarhus    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Esb       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Hern      .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_CA_Kal       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_CA_KBH       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Odense    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Randers   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_CA_Roenne    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_CA_TVIS      .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            343460
2050    .       DK_CA_Vestfrb   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_E_DTU        .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Grenaa    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Hil       .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Hjoerring .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Holst     .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Horsens   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_NrdOstSj  .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Silk      .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Sndborg   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MA_Viborg    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Aars     .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Frdhavn  .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Had      .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Hammel   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Hobro    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Naestved .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_NrAlslev .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Nyborg   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Nyk      .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Skagen   .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Slagelse .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Svend    .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS
2050    .       DK_MAM_Thisted  .       WOOD_PELLETS_GEN        .       WOOD_PELLETS_GEN_FLOW                                            EPS










/;



