SET PROCBUFFER(PROC) "Buffer processes (trace entering and/or leaving)"
/


Money_buffer
Money_buffer_T
GHG_Buffer
GHGbio_Buffer
GasBuffer
ElecBuffer
HeatBuffer
*BioSyngasBuffer
*BiogasBuffer

*DieselBuffer

*BiodieselBuffer
*MethanolBuffer
*EthanolBuffer

BioJetBuffer


Passenger_RE_fuels_Buffer
Freight_RE_fuels_Buffer


*----------------------------------------------------------------------------------------------------------------------------------------------------

/;
