
SET PROC "All 'transformations' that we use"
/
* NB: for debugging, print and ailing memory nice to have FLOW elements in UPPERCASE og Proc elements in CamelCase.

* The following three elements are obligatory (they will be used in the code as quoted elements)



Money_buffer
Money_buffer_T
GHG_Buffer
GHGbio_Buffer
GasBuffer
ElecBuffer
HeatBuffer
BioSyngasBuffer
BiogasBuffer
BiodieselBuffer
MethanolBuffer

EthanolBuffer

BioJetBuffer
BioGasolineBuffer



Linkstorage_Res


WOOD_GEN
STRAW_GEN
MUNI_WASTE_GEN
WOOD_PELLETS_GEN
MANURE_AND_WETBIO_GEN

WOOD_MASS
WOOD_PELLETS_MASS
STRAW_MASS
MUNI_WASTE_MASS
MANURE_AND_WETBIO_MASS


WOOD
WOOD_PELLETS
STRAW
MUNI_WASTE
MANURE_AND_WETBIO

MIX_FUEL

ProcEximTruck
ProcEximShip
ProcEximTrain

ThermGasific_SNG_50_WO
ThermGasific_SNG_50_WP
ThermGasific_SNG_50_ST
ThermGasific_SNG_50_MW

ThermGasific_SYNGAS_50_WO
ThermGasific_SYNGAS_50_WP
ThermGasific_SYNGAS_50_ST
ThermGasific_SYNGAS_50_MW


TG_50_WO
TG_50_WP
TG_50_ST
TG_50_MW


TG_FT_Biodiesel_50_WO
TG_FT_Biodiesel_50_WP
TG_FT_Biodiesel_50_ST
TG_FT_Biodiesel_50_MW



Biodiesel_FT_SUM


BIO_SNG_SUM
BIO_SNG_OUT


BIO_SYNGAS_GRID_IN
BIO_SYNGAS_GRID_OUT


BIO_TG_GRID_IN
BIO_TG_GRID_OUT


Tar
Digestate


SumSTWB

BiogasProd_single
BiogasProd_mix

BIOGAS_GRID_IN
BIOGAS_GRID_OUT



BiogasUpgr_BMETH_50


Electrolysis_H2Prod

HYDROGEN_GRID_IN
HYDROGEN_GRID_OUT

Hydrogen_STO_Large
HYDROGEN_After_STO_Large
Hydrogen_STO_Small
HYDROGEN_After_STO_Small

HYDROGEN_Before_USE
HYDROGEN_Use






Methanisation_Bio_BioGas
Methanisation_Gasif_BSNG
Methane_synthesis_TG_50
Methanol_synthesis_TG_50

Engine_SYNGAS_50
Engine_BIOGAS_50




Ethanol_50
BioJet_50


Methanol_car_eff
Ethanol_car_eff
Biodiesel_car_eff
BioGasoline_car_eff


Methanol_freight_eff
Ethanol_freight_eff
Biodiesel_freight_eff
BioGasoline_freight_eff



Passenger_RE_fuels_sum
Passenger_RE_fuels_Buffer


Freight_RE_fuels_sum
Freight_RE_fuels_Buffer
/;
