SET WASTETREATMENT 'Categories of waste treatment for building up output results'

/


$ontext

"Anaerobic Digestion"
"Biogas CHP"
"Biogas Upgrading"
"Collection"
"Electricity sold"
"Fertilizers"
"Heat sold"
"Incineration"
"Upgraded Biogas"
"Transport"
"Material Recovery Facility"
"Materials Recycled from MRF"
"Flexible Electricity"
"Flexible Heat"
"RDF Incineration"
"MSW CHP Large"
"MSW CHP Medium"
"MSW CHP Small"
"MSW Boiler"
"RDF CHP"
"RDF Boiler"
"Import of Waste"
"Heat cool down"


$offtext

/
;
